### ISSUE TITLE
Add Origin to Vary header

### ISSUE THREAD

**Issue by nikolas** [zestedesavoir/django-cors-middleware#10]
It sounds like `Origin` should be included in `Vary` in most cases. See:
https://github.com/cyu/rack-cors/blob/master/lib/rack/cors.rb#L93
https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Access-Control-Allow-Origin

**Comment by gustavi** [comment]
We will look this soon.

**Comment by sman591** [comment]
This was fixed in django-cors-headers back in 2016: https://github.com/adamchainz/django-cors-headers/pull/156

Is there any chance this same patch could be included for django-cors-middleware?

**Comment by artragis** [comment]
I will try to sync this project with upstream as soon as possible, I just need time.

**Comment by sman591** [comment]
@artragis If you have a moment and would accept it, I've copied over the patch from https://github.com/adamchainz/django-cors-headers/pull/156 in #45

**Comment by artragis** [comment]
https://pypi.org/project/django-cors-middleware/1.5.0/ is released
