### ISSUE TITLE
Add support for Django 1.10's new style middleware

### ISSUE THREAD

**Issue by edmorley** [zestedesavoir/django-cors-middleware#19]
Once #18 is merged, Travis will test django-cors-middleware under Django 1.10a1, with the middleware specified via the new `MIDDLEWARE` setting rather than the deprecated `MIDDLEWARE_CLASSES`. 

This currently fails, so a later PR will need to:
1) Use `django.utils.deprecation.MiddlewareMixin`
2) Decide how to handle non-HTTP200 responses, since the behaviour has now changed (ie unless special handling is added to django-cors-middleware, it will stop adding CORS headers to the responses of non-preflight requests - see the comment for the `test_middleware_integration_get_auth_view` test added in #18 for details). This may require subclassing `ExceptionMiddleware`.

For more info, see:
https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware

**Comment by edmorley** [comment]
My WIP branch is here:
https://github.com/edmorley/django-cors-middleware/compare/travis-django-110...edmorley:support-django-110

It addressed (1) above but not (2).

If someone wants to finish it off in the meantime (I may not have a chance to double back to this for a bit), feel free :-)

**Comment by edmorley** [comment]
Note that between Django 1.10a1 and 1.10b1 the new style middleware was tweaked further:
https://github.com/django/django/commit/7d1b69dbe7f72ac04d2513f0468fe2146231b286

Updated migration docs at:
https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-pre-django-1-10-style-middleware

**Comment by vhf** [comment]
Great, thanks for the update!

**Comment by helgi** [comment]
Threw in https://github.com/zestedesavoir/django-cors-middleware/pull/23 to have 1.10 tested (but still allow failures), hopefully we can get @edmorley PR over the line
