### ISSUE TITLE
Are you guys planning to update pypi to last version of this lib?

### ISSUE THREAD

**Issue by alexche8** [zestedesavoir/django-cors-middleware#30]
Please, it will be more comfortable to use

**Comment by gustavi** [comment]
Yes for sure ! Today or tommorow (currently have a batery issue on my laptop).

**Comment by gustavi** [comment]
1.3.1 (a pypi bug force me to user 1.3.1 instead of 1.3.0, sorry) is available !

**Comment by bluetech** [comment]
Hi @gustavi, it would be nice if you could sync the repo (currently at 1.3.0) with the pypi version (https://pypi.python.org/pypi/django-cors-middleware/1.3.1), otherwise without your comment here it looks a bit suspicious :)

**Comment by gustavi** [comment]
Fore sure.
