### ISSUE TITLE
Confused by the v3.4.0 release tag: I think it should be v1.4.0?

### ISSUE THREAD

**Issue by stig** [zestedesavoir/django-cors-middleware#43]
Dependabot allerted us to a new release, 1.4.0. I viewed the [GitHub releases](https://github.com/zestedesavoir/django-cors-middleware) page to see what the changes were in this release, but was initially confused because I couldn't find a v1.4.0 release tag. It looks like the most recent release is incorrectly tagged v3.4.0, because it links to v1.4.0 on pypi.

If this was indeed done in error it may be a good idea to create a new v1.4.0 release tag as a clone of the v3.4.0 one and update the latter's description saying it was a mistake.

**Comment by artragis** [comment]
nice catch, will fix it asap. thanks for the contribution.

**Comment by artragis** [comment]
Fixed.
