### ISSUE TITLE
Add DNT to default CORS headers

### ISSUE THREAD

**Issue by ssaavedra** [zestedesavoir/django-cors-middleware#8]
As per issue in https://github.com/ottoyiu/django-cors-headers/issues/78 , it seems the DNT header is common (and safe) enough so that it should not invalidate CORS in the preflight request.

**Comment by gustavi** [comment]
We will look this soon

**Comment by ssaavedra** [comment]
Hi, I do not see this discussion started anywhere. Why should the DNT header not be added by default?

**Comment by melizeche** [comment]
Maybe close this issue? it seems it got merged in #141
